#!/bin/sh
#artix desktop install
sudo ln -s /etc/runit/sv/NetworkManager /run/runit/service
sh subscripts/mirrors
sh subscripts/yay-install
sh subscripts/yay-desktop 
sh subscripts/misc
sudo mkinitcpio -P

ln -s /etc/runit/sv/lightdm /run/runit/service

