#!/bin/sh
sudo pacman -S reflector --noconfirm
sudo cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.old
sudo reflector --verbose --latest 20 --sort rate --save /etc/pacman.d/mirrorlist


sudo pacman -Sy git qbittorrent xclip python-pywal xorg vlc gtop htop vim firefox spectacle libreoffice-fresh numlockx pulseaudio amd-ucode galculator ntfs-3g lightdm  picom lightdm-gtk-greeter feh w3m yad xdotool code kitty pulseaudio-alsa alsa-oss nemo ranger dunst xf86-video-amdgpu lxappearance gimp alsa-firmware --noconfirm

cd
git clone https://github.com/edwardbas-pl/dmenu.git
cd dmenu
sudo make install
rm -rf dmenu
cd
git clone https://aur.archlinux.org/yay-git.git
cd yay-git
makepkg -si --noconfirm
cd
rm -rf yay-git
yay -S pfetch ttf-symbola polybar udisks2 i3-gaps-rounded-git lightdm-slick-greeter lightdm-settings apulse ttf-dejavu ttf-liberation --noconfirm
cd
git clone https://github.com/cttynul/gimpshop-reloaded.git
cd gimpshop-reloaded
chmod +x linux-install-2.10.sh
./linux-install-2.10.sh
cd
git clone https://github.com/edwardbas-pl/backup.git
cd backup
./Restore
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

ln -s /run/media/$USER/     ~/Media


sudo systemctl enable lightdm
systemctl enable --user dunst
systemctl start --user dunst
