#!/bin/sh
#arch laptop install script

#detect Arch vs Artix(runit version)
distro=$( grep -m 1 NAME /etc/os-release )
if [[ ${distro} == *Arch* ]];
then
	sh subscripts/mirrors
fi

sh subscripts/yay-install
sh subscripts/yay-universal
sh subscripts/yay-laptop
sh subscripts/misc
sudo mkinitcpio -P


if [[ ${distro} == *Arch* ]];
then
	sudo systemctl start lightdm
fi

if [[ ${distro} == *Artix* ]];
then
	sudo ln -s /etc/runit/sv/lightdm /etc/runit/service
	sudo ln -s /etc/runit/sv/NetworkManager /etc/runit/service
fi

