#!/bin/sh
pacman -Sy git dialog
DESKTOP=$( dialog --menu --stdout "Chose your Desktop" 10 60 10 i3 "customized i3 desktop with polybar" bspwm "bspwm and polybar with rounded corners" Gnome "minimal Gnome Desktop Enviornment")
$TERMINAL = kitty
clear

echo $DESKTOP
if [ $DESKTOP = i3 ]
then
    yay -S i3-gaps
elif [ $DESKTOP = Gnome ]
then
    pacman -S gnome-shell gnome-tweak-tool gnome-control-center 
elif [ $DESKTOP = bspwm ]
then
    yay -S bspwm sxhkd
fi

yay -S $TERMINAL 