#!/bin/bash

distro=$(grep -m 1 NAME /etc/os-release)
yay -S --noconfirm qemu virt-manager dnsmasq ebtables

if [[ ${distro} == *Arch* ]];
then
	sudo systemctl start --now libvirtd
fi

if [[ ${distro} == *Artix* ]];
then
	sudo ln -s /etc/runit/sv/libvirtd /etc/runit/service
fi
