#!/bin/bash

sudo sed -i "/\[multilib\]/,/Include/"'s/^#//' /etc/pacman.conf

#wine dependencies
sudo pacman -Sy --noconfirm wine-staging giflib lib32-giflib libpng lib32-libpng libldap lib32-libldap gnutls lib32-gnutls mpg123 lib32-mpg123 openal lib32-openal v4l-utils lib32-v4l-utils libpulse lib32-libpulse libgpg-error lib32-libgpg-error alsa-plugins lib32-alsa-plugins alsa-lib lib32-alsa-lib libjpeg-turbo lib32-libjpeg-turbo sqlite lib32-sqlite libxcomposite lib32-libxcomposite libxinerama lib32-libgcrypt libgcrypt lib32-libxinerama ncurses lib32-ncurses opencl-icd-loader lib32-opencl-icd-loader libxslt lib32-libxslt libva lib32-libva gtk3 lib32-gtk3 gst-plugins-base-libs lib32-gst-plugins-base-libs vulkan-icd-loader lib32-vulkan-icd-loader

#vulkan
GPU=$(lspci | grep -i --color "vga\|3d\|2d")
if [[ ${GPU} == *Radeon* ]];
then
	echo "your GPU vendor is AMD"
	sudo pacman -S --needed lib32-vulkan-radeon vulkan-radeon
	sudo pacman -Sy --nonconfitm ib32-mesa vulkan-radeon lib32-vulkan-radeon vulkan-icd-loader lib32-vulkan-icd-loader
fi
if [[ ${GPU} == *Intel* ]];
then
	echo "your GPU vendor is Intel"
	sudo pacman -S --needed lib32-vulkan-intel vulkan-intel
	sudo pacman -Sy --noconfirm lib32-mesa vulkan-intel lib32-vulkan-intel vulkan-icd-loader lib32-vulkan-icd-loader
fi
if [[ ${GPU} == *NV* ]];
then
	echo "your GPU vendor is NVidia"
	sudo pacman -S --needed lib32-nvidia-utils nvidia libglvnd lib32-libglvnd
	sudo pacman -Sy --noconfirm nvidia-dkms nvidia-utils lib32-nvidia-utils nvidia-settings vulkan-icd-loader lib32-vulkan-icd-loaderfi
fi
wine and other packages
sudo pacman -S --needed cabextract dosbox giflib gnutls gst-plugins-base-libs lib32-giflib lib32-gnutls lib32-gst-plugins-base-libs lib32-libcurl-gnutls lib32-libgcrypt lib32-libjpeg-turbo lib32-libpng lib32-libva lib32-libxslt lib32-mpg123 lib32-openal lib32-opencl-icd-loader lib32-sdl2 lib32-vkd3d lib32-vulkan-icd-loader libcurl-gnutls libgcrypt libjpeg-turbo libpng libva libxslt mono mpg123 openal opencl-icd-loader vkd3d vulkan-icd-loader wine-staging zstd gamemode lib32-gamemode 
yay -S dxvk-bin
#game launchers
yay -Sy --noconfirm lutris steam gamemode
