#!/bin/sh
#desktop install script
yay -S --noconfirm  git qbittorrent xclip python-pywal i3-gaps xorg vlc gtop htop vim firefox spectacle libreoffice-fresh numlockx pulseaudio galculator ntfs-3g lightdm lightdm-gtk-greeter feh w3m yad xdotool kitty pulseaudio-alsa alsa-oss nemo ranger dunst xf86-video-amdgpu lxappearance gimp alsa-firmware 
